version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: api
    container_name: api
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - node-network

  nginx-setup:
    image: nginx:mainline-alpine
    container_name: nginx-setup
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx/setup:/etc/nginx/conf.d
      - web-root:/var/www/html
    depends_on:
      - api
    networks:
      - node-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx-setup
    command: certonly --webroot --webroot-path=/var/www/html --email vinybergamo@gmail.com --agree-tos --no-eff-email -d docker.vinybergamo.com
    networks:
      - node-network

  nginx-production:
    image: nginx:mainline-alpine
    container_name: nginx-production
    restart: unless-stopped
    ports:
      - 443:443
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
      - dhparam:/etc/ssl/certs
      - ./nginx/production:/etc/nginx/conf.d
    depends_on:
      - api
      - nginx-setup
    networks:
      - node-network

volumes:
  certbot-etc:
  certbot-var:

  web-root:
    driver: local
    driver_opts:
      type: none
      device: ./
      o: bind

  dhparam:
    driver: local
    driver_opts:
      type: none
      device: ./dhparam
      o: bind

networks:
  node-network:
    driver: bridge
